/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package punto_venta.Panels;


import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;

/**
 *
 * @author israe
 */
public class inicioPanel extends javax.swing.JPanel {

    /**
     * Creates new form inicioPanel
     */
     
    public inicioPanel() {
        
        initComponents();
       initStyles();
       //this.setLayout(new BorderLayout());
    }
    
    private void initStyles(){
    parrafo1.putClientProperty( "FlatLaf.style", "font: bold  20 regular.font" );
    parrafo1.setForeground(Color.white);
    parrafo2.putClientProperty( "FlatLaf.style", "font:   18 regular.font" );
    parrafo2.setForeground(Color.white);
    parrafo3.putClientProperty( "FlatLaf.style", "font:  18 regular.font" );
    parrafo3.setForeground(Color.white);
    parrafo4.putClientProperty( "FlatLaf.style", "font:   18 regular.font" );
    parrafo4.setForeground(Color.white);
    parrafo5.putClientProperty( "FlatLaf.style", "font:  18 regular.font" );
    parrafo5.setForeground(Color.white);
    parrafo6.putClientProperty( "FlatLaf.style", "font: bold 20 regular.font" );
    parrafo6.setForeground(Color.white);
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        imagen = new javax.swing.JLabel();
        parrafo1 = new javax.swing.JLabel();
        parrafo2 = new javax.swing.JLabel();
        parrafo3 = new javax.swing.JLabel();
        parrafo4 = new javax.swing.JLabel();
        parrafo5 = new javax.swing.JLabel();
        parrafo6 = new javax.swing.JLabel();

        background.setBackground(new java.awt.Color(0, 0, 0));
        background.setPreferredSize(new java.awt.Dimension(750, 460));

        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoJuan (1).jpg"))); // NOI18N

        parrafo1.setText("       Bienvenidos a el sistema de ventas donde podras: ");

        parrafo2.setText("     ➣  Controlar accesos ");

        parrafo3.setText("     ➣  Ver las ventas de un mes especifico");

        parrafo4.setText("     ➣  Cobrar tus productos rapidamente");

        parrafo5.setText("     ➣  Cobrar tus productos rapidamente");

        parrafo6.setText(" PUNTO DE VENTA PARA TIENDA DE ABARROTES");

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(506, 506, 506)
                        .addComponent(imagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(parrafo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(parrafo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(parrafo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(parrafo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(parrafo5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(parrafo6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(2, 2, 2))))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(parrafo1, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(parrafo2, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(parrafo4, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addGap(24, 24, 24)
                .addComponent(parrafo3, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addGap(24, 24, 24)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(parrafo5, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                        .addGap(242, 242, 242))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(parrafo6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(102, 102, 102))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(imagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel imagen;
    private javax.swing.JLabel parrafo1;
    private javax.swing.JLabel parrafo2;
    private javax.swing.JLabel parrafo3;
    private javax.swing.JLabel parrafo4;
    private javax.swing.JLabel parrafo5;
    private javax.swing.JLabel parrafo6;
    // End of variables declaration//GEN-END:variables
}
