/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package punto_venta;

import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterIJTheme;
import constructor.constructor;
import java.awt.Toolkit;
import javax.swing.JDialog;
import javax.swing.JOptionPane;


/**
 *
 * @author israe
 */
public class ventanaLogin extends javax.swing.JFrame {

    /**
     * Creates new form ventanaLogin
     */
    int xMause, yMause;
    
    public ventanaLogin() {
        initComponents();
        JlabelOcultar.setVisible(false);
//        this.setExtendedState(6);
        txtUsuario.putClientProperty("JTextField.placeholderText", "Ingresa Correo o Telefono.");
        jPassword.putClientProperty("JTextField.placeholderText", "Ingresa Tu contraseña");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabelCerrrar = new javax.swing.JLabel();
        jPanelCierra = new javax.swing.JPanel();
        JlabelOcultar = new javax.swing.JLabel();
        JlabelVer = new javax.swing.JLabel();
        backGroundEyes = new javax.swing.JPanel();
        jPassword = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabelBtnIngresar = new javax.swing.JLabel();
        jLabelBtnCancelar = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 57, 146));
        jPanel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel4MouseDragged(evt);
            }
        });
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel4MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 30));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carrito super-modi-modified.png"))); // NOI18N
        jLabel1.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SISTEMA");

        jLabel4.setFont(new java.awt.Font("Baskerville Old Face", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DE VENTAS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 510));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("contraseña");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 450, 40));

        txtUsuario.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuario.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(0, 0, 0));
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.red, new java.awt.Color(204, 0, 0)));
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsuarioMouseClicked(evt);
            }
        });
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyPressed(evt);
            }
        });
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 420, 40));

        jLabelCerrrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCerrrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/X.png"))); // NOI18N
        jLabelCerrrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCerrrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCerrrarMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelCerrrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 30, 30));

        jPanelCierra.setBackground(new java.awt.Color(255, 51, 102));

        javax.swing.GroupLayout jPanelCierraLayout = new javax.swing.GroupLayout(jPanelCierra);
        jPanelCierra.setLayout(jPanelCierraLayout);
        jPanelCierraLayout.setHorizontalGroup(
            jPanelCierraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanelCierraLayout.setVerticalGroup(
            jPanelCierraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanelCierra, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 30, 30));

        JlabelOcultar.setBackground(new java.awt.Color(255, 255, 255));
        JlabelOcultar.setForeground(new java.awt.Color(255, 255, 255));
        JlabelOcultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/EyeOculta.png"))); // NOI18N
        JlabelOcultar.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 2, 2, new java.awt.Color(255, 0, 0)));
        JlabelOcultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JlabelOcultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JlabelOcultarMouseClicked(evt);
            }
        });
        jPanel1.add(JlabelOcultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 280, -1, 40));

        JlabelVer.setBackground(new java.awt.Color(255, 255, 255));
        JlabelVer.setForeground(new java.awt.Color(255, 255, 255));
        JlabelVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/eyeVER.png"))); // NOI18N
        JlabelVer.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 2, 2, new java.awt.Color(255, 0, 0)));
        JlabelVer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JlabelVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JlabelVerMouseClicked(evt);
            }
        });
        jPanel1.add(JlabelVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 280, -1, 40));

        backGroundEyes.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout backGroundEyesLayout = new javax.swing.GroupLayout(backGroundEyes);
        backGroundEyes.setLayout(backGroundEyesLayout);
        backGroundEyesLayout.setHorizontalGroup(
            backGroundEyesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        backGroundEyesLayout.setVerticalGroup(
            backGroundEyesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(backGroundEyes, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 280, 50, 40));

        jPassword.setBackground(new java.awt.Color(255, 255, 255));
        jPassword.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jPassword.setForeground(new java.awt.Color(0, 0, 0));
        jPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 0, new java.awt.Color(255, 0, 0)));
        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });
        jPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordKeyPressed(evt);
            }
        });
        jPanel1.add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 370, 40));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("usuario");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 450, 40));

        jLabelBtnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/buttonIngresar.png"))); // NOI18N
        jLabelBtnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelBtnIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBtnIngresarMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelBtnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 410, -1, -1));

        jLabelBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/buttonCancelar.png"))); // NOI18N
        jLabelBtnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelBtnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBtnCancelarMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelBtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/toluca_portales_puntoventa.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 450, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JlabelOcultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlabelOcultarMouseClicked
        // TODO add your handling code here:
        JlabelVer.setVisible(true);
        JlabelOcultar.setVisible(false);
        jPassword.setEchoChar('●');
    }//GEN-LAST:event_JlabelOcultarMouseClicked

    private void JlabelVerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlabelVerMouseClicked
        // TODO add your handling code here:
        JlabelVer.setVisible(false);
        JlabelOcultar.setVisible(true);
        jPassword.setEchoChar((char)0);
    }//GEN-LAST:event_JlabelVerMouseClicked

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    private void jLabelBtnIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnIngresarMouseClicked
        constructor ingresa=new constructor();
        String usuario, contrasena;
        usuario=txtUsuario.getText();
        contrasena=jPassword.getText();
       String[] resultado = ingresa.Login(usuario, contrasena);
       String acceso = resultado[0];
       String nombre = resultado[1];
        if ("ADMINISTRADOR".equals(acceso)) {
            JOptionPane.showMessageDialog(null, "BIENVENIDO " + acceso+ " "+ nombre);
            menuAdmin MA=new menuAdmin(nombre);
            MA.setVisible(true);
            
        }else if("VENDEDOR".equals(acceso)){
            JOptionPane.showMessageDialog(null, "BIENVENIDO :3" + acceso+ " "+nombre);        
        }
        dispose();
    }//GEN-LAST:event_jLabelBtnIngresarMouseClicked

    private void jLabelCerrrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrrarMouseClicked

        // Configuración del cuadro de diálogo de confirmación
        JOptionPane optionPane = new JOptionPane("¿Estás seguro de cerrar el sistema de ventas?", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION);

        // Establece que el cuadro de diálogo sea siempre superior


        // Muestra el cuadro de diálogo de confirmación
        JDialog confirmationDialog = optionPane.createDialog("Confirmar cierre");
        confirmationDialog.setModal(true);
        confirmationDialog.setAlwaysOnTop(true);
        confirmationDialog.setVisible(true);

        // Emitir un sonido de Windows
        Toolkit.getDefaultToolkit().beep();

        // Obtén la opción seleccionada por el usuario
        int confirmacion = (Integer) optionPane.getValue();

        if (confirmacion == JOptionPane.YES_OPTION) {
            // Si el usuario elige "Sí", cierra el sistema
            System.exit(0);
        }

    }//GEN-LAST:event_jLabelCerrrarMouseClicked

    private void jLabelBtnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnCancelarMouseClicked
//         TODO add your handling code here:
        // Configuración del cuadro de diálogo de confirmación
        JOptionPane optionPane = new JOptionPane("¿Estás seguro de cancelar", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION);

        // Establece que el cuadro de diálogo sea siempre superior


        // Muestra el cuadro de diálogo de confirmación
        JDialog confirmationDialog = optionPane.createDialog("Confirmar cancelacion");
        confirmationDialog.setModal(true);
        confirmationDialog.setAlwaysOnTop(true);
        confirmationDialog.setVisible(true);

        // Emitir un sonido de Windows
        Toolkit.getDefaultToolkit().beep();

        // Obtén la opción seleccionada por el usuario
        int confirmacion = (Integer) optionPane.getValue();

        if (confirmacion == JOptionPane.YES_OPTION) {
            // Si el usuario elige "Sí", cierra el sistema
            System.exit(0);
        }
    }//GEN-LAST:event_jLabelBtnCancelarMouseClicked

    private void txtUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtUsuarioMouseClicked

    private void jPanel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MousePressed
        // TODO add your handling code here:
        xMause=evt.getX();
        yMause=evt.getY();
    }//GEN-LAST:event_jPanel4MousePressed

    private void jPanel4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x - xMause, y - yMause);
    }//GEN-LAST:event_jPanel4MouseDragged

    private void txtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
        // Cuando se presiona Enter en la primera caja de texto, pasa el foco a la siguiente caja de texto
        jPassword.requestFocus();
    }
    }//GEN-LAST:event_txtUsuarioKeyPressed

    private void jPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
        jLabelBtnIngresar.requestFocus();
        jLabelBtnIngresarMouseClicked(null);
    }
    }//GEN-LAST:event_jPasswordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ventanaLogin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlabelOcultar;
    private javax.swing.JLabel JlabelVer;
    private javax.swing.JPanel backGroundEyes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelBtnCancelar;
    private javax.swing.JLabel jLabelBtnIngresar;
    private javax.swing.JLabel jLabelCerrrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelCierra;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

   

}
